# conda env create -f environment.yml
name: bpy_lattice-dev
channels:
  - conda-forge
dependencies:
  - python==3.11 # Required for latest Blender
  - numpy
  # - openusd  # using PyPI dep for now due to this: https://github.com/conda-forge/openusd-feedstock/issues/9
  # Developer
  - openpmd-beamphysics
  - pytao >0.5.2
  - pytest
  - pytest-cov
  - jupyterlab>=3
  - pygments
  - mkdocs
  - mkdocstrings
  - mkdocs-material
  - mkdocs-jupyter
  - mkdocstrings-python
  - pip
  - pip:
      - bpy
      - usd-core
