# conda env create -f environment.yml
name: bpy_lattice-dev
channels:
  - conda-forge
dependencies:
  - python==3.11 # Required for latest Blender
  - numpy
  - openusd
  # Developer
  - openpmd-beamphysics
  - pytao >0.5.2
  - pytest
  - pytest-cov
  - jupyterlab>=3
  - pygments
  - mkdocs #==1.5.2
  - mkdocstrings
  - mkdocs-material
  - mkdocs-jupyter #==0.24.6
  - mkdocstrings-python
  - pip
  - pip:
      - bpy
