# conda env create -f environment.yml
name: bpy_lattice-dev
channels:
  - conda-forge
dependencies:
  - python==3.13 # Required for latest Blender 5.1
  - numpy
  # Developer
  - openpmd-beamphysics
  - pytao >0.5.2
  - pytest
  - pytest-cov
  - jupyterlab>=3
  - pygments
  - mkdocs
  - mkdocstrings
  - mkdocs-material
  - mkdocs-jupyter
  - mkdocstrings-python
  - pip
  - pip:
      - bpy
      #- usd-core
