from enum import StrEnum


class ApertureType(StrEnum):
    RECTANGULAR = "rectangular"
    ELLIPTICAL = "elliptical"
    WALL3D = "wall3d"


class KeyType(StrEnum):
    AB_MULTIPOLE = "ab_multipole"
    AC_KICKER = "ac_kicker"
    BEAMBEAM = "beambeam"
    BEGINNING_ELE = "beginning_ele"
    CONVERTER = "converter"
    CRAB_CAVITY = "crab_cavity"
    CUSTOM = "custom"
    DRIFT = "drift"
    E_GUN = "e_gun"
    ECOLLIMATOR = "ecollimator"
    ELSEPARATOR = "elseparator"
    EM_FIELD = "em_field"
    FEEDBACK = "feedback"
    FIDUCIAL = "fiducial"
    FLOOR_SHIFT = "floor_shift"
    FOIL = "foil"
    FORK = "fork"
    GKICKER = "gkicker"
    HKICKER = "hkicker"
    HYBRID = "hybrid"
    INSTRUMENT = "instrument"
    KICKER = "kicker"
    LCAVITY = "lcavity"
    MARKER = "marker"
    MASK = "mask"
    MATCH = "match"
    MONITOR = "monitor"
    MULTIPOLE = "multipole"
    NULL_ELE = "null_ele"
    OCTUPOLE = "octupole"
    PATCH = "patch"
    PHOTON_FORK = "photon_fork"
    PIPE = "pipe"
    QUADRUPOLE = "quadrupole"
    RCOLLIMATOR = "rcollimator"
    RF_BEND = "rf_bend"
    RFCAVITY = "rfcavity"
    SAD_MULT = "sad_mult"
    SBEND = "sbend"
    SEXTUPOLE = "sextupole"
    SOL_QUAD = "sol_quad"
    SOLENOID = "solenoid"
    TAYLOR = "taylor"
    THICK_MULTIPOLE = "thick_multipole"
    UNDULATOR = "undulator"
    VKICKER = "vkicker"
    WIGGLER = "wiggler"
